name: tejas
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7 
  fl_chart: ^0.63.0
  flutter_screenutil: ^5.8.4
  dotted_border: ^2.0.0
  image_picker: ^1.1.0
  file_picker: ^6.1.1 
  flutter_rating_bar: ^4.0.1
  video_player: ^2.5.1
  camera: ^0.10.5+5
  agora_rtc_engine: ^6.1.1  # Check for latest version on pub.dev
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/onboarding1.jpg
    - assets/onboarding2.jpg
    - assets/onboarding3.jpg
    - assets/india_flag.png
    - assets/login_bottom.png
    - assets/login_page_image.png
    - assets/gender_image.jpg
    - assets/hat.jpg
    - assets/science_lab.jpg
    - assets/commerce_illustration.jpg
    - assets/arts_illustration.jpg
    - assets/others_illustration.jpg
    - assets/session_illustration.jpg
    - assets/location_illustration.jpg
    - assets/your_illustration.jpg
    - assets/video_upload_illustration.jpg
    - assets/approval_image.jpg
    - assets/grammar_icon.jpg
    - assets/ai_icon.jpg
    - assets/talk_icon.jpg
    - assets/reading.jpg
    - assets/manage_tasks.jpg
    - assets/chart.jpg
    - assets/bot.jpg
    - assets/user.jpg
    - assets/bot1.jpg
    - assets/user1.jpg
    - assets/user2.jpg
    - assets/user3.jpg
    - assets/male.png
    - assets/female.png
    - assets/wave.jpg
    - assets/plan1.jpg
    - assets/plan2.jpg
    - assets/plan3.jpg
    - assets/plan4.jpg
    - assets/tutor.jpg
    - assets/student.jpg
    - assets/meetup.jpg
    - assets/tutor1.jpg
    - assets/tutor2.jpg
    - assets/checkmark.jpg
    - assets/thankyou_illustration.jpg
    - assets/listening.mp4